### ISSUE TITLE
"Delete" cluster doesn't do anything

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#104]
## What versions of software are you using?
- Operating System: MacOS
- IntelliJ version: 2018.2
- intellij-openshift-connector 1.0.0
- OpenShift version: -

## What did you run exactly?
1. ASSERT: have a ~/.kube/config with several clusters defined
1. EXEC: In Clusters view select a cluster and pick "Delete" in the ctx menu

## Actual behavior
Does nothing

## Expected behavior
Deletes the selected cluster(s)

**Comment by adietish** [comment]
weird, I now have delete working. Not sure what the conditions are so that one can reproduce this. Will keep investigating.

**Comment by sbouchet** [comment]
closing as we now depends on intellij-kubernetes to manage clusters (#319)
