### ISSUE TITLE
Dont see that "Set Current" is in progress

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#105]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Steps:
1. ASSERT: have ~/.kube/config with several clusters
1. EXEC: in "Clusters" view pick "Set Current" in ctx menu of a cluster

Result: 
At first nothing happens. There's no hour glass nor any sort of feedback that the operation is in progress. After a few seconds only I see the OpenShift explorer being updated to cluster that I selected.

**Comment by adietish** [comment]
This is true for most operations. There is no feedback in UI. As a user I thus keep wondering if it worked or not until - several seconds later - the result gets visible.

**Comment by jeffmaury** [comment]
Closing as we are not using intellij-kubernetes
