### ISSUE TITLE
Unclear how to add a new cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#106]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Steps:
1. ASSERT: have a cluster active in the "OpenShift Explorer"
1. EXEC: right click into empty space

Result:
A context menu with "Nothing here" appears. To a dummy user it's unclear how he'd now add a new cluster. 
![image](https://user-images.githubusercontent.com/25126/68122560-e1873080-ff0a-11e9-809b-36a4e1212e2e.png)
It's only after trying that you find out that you can "Log out" of your cluster, "Log in to cluster" and change the url. Alternatively you can pick a cluster in the clusters view.

**Comment by mohitsuman** [comment]
@adietish Do you still face the same issue ?

**Comment by mohitsuman** [comment]
<img width="674" alt="Screenshot 2022-08-27 at 9 29 37 PM" src="https://user-images.githubusercontent.com/3133356/187038083-f8ed4c17-0244-4ade-8877-4fb5d65e1598.png">

As per the latest extension, clicking on the empty box shows the Login information. Hence closing this.
