### ISSUE TITLE
Cluster login dialog should allow to use login command that I get from the web console

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#109]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
In the web console, one can copy the login command that is for the oc command.
Currently, to use this command that the web console copies to my clipboard, I'd have to either execute it in a terminal or paste it into an editor and extract the cluster url and the token (in 2 steps).
It would be very handy (as it turned out in Eclipse OpenShift tooling) if the intellij-openshift-connector would allow me to use it directly.
It could paste it into the form if there's no current cluster. If there is one we could ex. allow to use it via hitting a button, link etc.

**Comment by jeffmaury** [comment]
Duplicates #39
