### ISSUE TITLE
"Delete" several selected clusters only deletes the 1st one 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#118]
[kind/bug]

Steps:
1. ASSERT: have several clusters defined in ~/.kube/config
1. EXEC: in "Clusters" view: select several clusters
1. EXEC: pick "Delete" in ctx menu

Result:
Only the 1st selected cluster is removed, leaving the other ones in place
Thanks for understanding, and for contributing to the project!

**Comment by mohitsuman** [comment]
@adietish Deleting multiple clusters at one point is not feasible doing via odo. As odo runs single command for one operation.
