### ISSUE TITLE
Explorer: A spinner (progress indicator) should inform that the unfolded node is loading it's children

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#124]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
If you unfold ex. a project node in the explorer, you notice a slight delay until the project lists its applications. This delay is caused by odo loading the applications for the project. While the loading is in progress, nothing happens, the tree seems frozen. Even though this is not a very long wait (depending on your network- and cluster-speed) this inactivity is confusing/annoying. IntelliJ encourages using progress indicators for tree nodes . when loading happens so that the user has immediate feedback: https://jetbrains.github.io/ui/controls/progress_indicators/#tree-list-tool-window
We should show a Loading node with a spinner (or display a spinner in the parent node) while the node is loading it's children.
![image](https://user-images.githubusercontent.com/25126/68287042-5b8df580-0082-11ea-9600-bd159e225611.png)
btw. vscode-openshift-connector does exactly this, it is displaying a spinner while the node is loading it's children.

**Comment by jeffmaury** [comment]
Will be achieved by switching to the structure tree and async loading

**Comment by jeffmaury** [comment]
Depends on #274
