### ISSUE TITLE
Create component: cannot get to previous step

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#128]
[kind/bug]

## What did you run exactly?
1. ASSERT: have cluster with a project
1. EXEC: in Explorer: pick "Create Component", pick "Binary" for "Source type:", hit "Next"
1. ASSERT: "Binary file" page shows up
1. EXEC: hit "Previous >"

## Actual behavior
Nothing happens, wizard stays in "Binary file" page

## Expected behavior
Should get back to previous page for the component

**Comment by mohitsuman** [comment]
@adietish In future release of the extension, git and binary file support will be removed. Hence closing this issue.
