### ISSUE TITLE
All source files should comply to same formatting

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#130]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Currently code formatting is not consistent: some source files indent by 4, some by 2

**Comment by sbouchet** [comment]
@adietish: several idées : 
- use checkstyle with built-in IDE support
- use sonarcloud and add the project to https://sonarcloud.io/organizations/redhat-developer/projects.

**Comment by sbouchet** [comment]
@jkopriva: maybe you can help to set up sonarcloud for this repo ?

**Comment by jkopriva** [comment]
@sbouchet I can look into it, can you please assigned it to me? i do not have permissions for this repo.

**Comment by sbouchet** [comment]
@jkopriva I'll create a specific issue for this.

**Comment by mohitsuman** [comment]
@adietish We now support sonar and IDE checkstyle. Closing this issue.
