### ISSUE TITLE
Uniformise link parameters to conform with API 

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#159]
curently the link APi is described like: 
```void link(String project, String application, String component, String context, String source, Integer port) throws IOException;```
but the other API parameters are listed like:
``` ... String project, String application, String context, String component, ... ```

We should use the same parameter list for all our API

**Comment by mohitsuman** [comment]
@sbouchet This looks fixed, right ?

**Comment by sbouchet** [comment]
@mohitsuman  no, issue still exists.

**Comment by sbouchet** [comment]
fixed with https://github.com/redhat-developer/intellij-openshift-connector/pull/360/commits/4f9ef5b640e8eced4fd173565b1637922303a4cd
