### ISSUE TITLE
'Describe' command for Storage

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#180]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

See https://github.com/redhat-developer/vscode-openshift-tools/issues/1459
or https://issues.redhat.com/browse/JBIDE-27126

**Comment by sbouchet** [comment]
We have to wait for openshift/odo#2638 to be merged.

**Comment by mohitsuman** [comment]
odo now has support for `odo url list`. Hence describe command is not going to be implemented. Closing this issue.
