### ISSUE TITLE
`Describe` command for URL's

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#181]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

See https://github.com/redhat-developer/vscode-openshift-tools/issues/1458
or https://issues.redhat.com/browse/JBIDE-27127

**Comment by sbouchet** [comment]
We have to wait for https://github.com/openshift/odo/issues/2638 to be merged.

**Comment by mohitsuman** [comment]
This command is permanently removed form odo. Closing.
