### ISSUE TITLE
If there are no service available in the catalog, UI is shown with an error.

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#226]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Improve the error message by an information window.

## Why is this needed? 
align with other tooling experience.

see https://github.com/jbosstools/jbosstools-openshift/pull/1946#issuecomment-696028705 for initial request.

**Comment by jeffmaury** [comment]
Did you test it ? According to https://github.com/redhat-developer/intellij-openshift-connector/blob/master/src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java#L68 you should get the proper error message

**Comment by sbouchet** [comment]
Yes i tested it but unfortunately, the line is never reached as the gettemplates() method throw an error : 
 {
	"kind": "Error",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"creationTimestamp": null
	},
	"message": "no deployable services found"
}
So this dialog do not show, only the one below with the Error title : 
![Capture d’écran de 2020-09-22 10-30-23](https://user-images.githubusercontent.com/600414/93860005-a7f41b00-fcbe-11ea-8d9f-6867dd51fcba.png)

Tested in VSCode, when creating a service, a notification is shown with the "no deployable services found" message.

**Comment by sbouchet** [comment]
depends on https://github.com/openshift/odo/issues/4024
