### ISSUE TITLE
"About" item does nothing after click (when you are not logged in any cluster)

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-openshift-connector#239]
<img width="557" alt="Snímek obrazovky 2020-11-06 v 9 43 00" src="https://user-images.githubusercontent.com/43820055/98345124-86ec4d00-2014-11eb-89d9-156e03d94cd1.png">

**Comment by mohitsuman** [comment]
@sbouchet Can you please take a look at this and confirm if it still persists in the latest extension ?

**Comment by sbouchet** [comment]
closing as it's now opens a terminal with the odo version only, as expected.
