### ISSUE TITLE
Add telemetry information for OpenShift cluster version

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#317]
### Goal
Provide the OpenShift cluster version information the user connects to through the extension

### Acceptance Criteria

- The extension should send data to telemetry, regarding the connectedOpenShift cluster version.
- This should cover OpenShift 3.x and 4.x clusters

VSCode Reference: https://github.com/redhat-developer/vscode-openshift-tools/issues/2149

**Comment by jeffmaury** [comment]
The following information will be recorded:
- Kubernetes version
- flag for OpenShift/Kubernetes cluster type
- OpenShift version (may be absent on OCP4 and non admin access)

A utility will be provided in IntelliJ common to retrieve these infos as IJ Tekton and IJ Knative may also require it
