### ISSUE TITLE
Depend on Kubernetes extension for cluster managment

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#319]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
As the Kubernetes extension from Red Hat is now available, there is no need to have our own cluster view for managing contexts. Let's remove it and only use the current context from this extension.

**Comment by mohitsuman** [comment]
@sbouchet How is the context managed now ? Is the option to switch context available on the cluster itself on the OpenShift extension ?

**Comment by sbouchet** [comment]
@mohitsuman : as you can see on this animation[1], there is actually a cluster view below the application explore that displays context and have two actions : Use the selected entry as the current context, and a delete context. so there is no switch context on the openshift explorer view and we would like to use the kubernetes extension to do so. 

[1] https://github.com/redhat-developer/intellij-openshift-connector/raw/main/images/0.4.0/openshift1.gif
