### ISSUE TITLE
Couldn't log in to Openshift v4.6 and get freeze IDE (odo v2.0.7, idea 2021.1.2, plugin v0.6.0.56)

### ISSUE THREAD

**Issue by NKozlov** [redhat-developer/intellij-openshift-connector#323]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS Catalina (10.15.7)
- IntelliJ version: 2021.1.2
- OpenShift version: 4.6 (OCP)

## What did you run exactly?
I tried to log in

## Actual behavior
Doesn't log in and get to freeze IDE.

## Expected behavior
Log in and works.

## Any logs, error output, etc?
If say where I can get logs, I give you.

**Comment by jeffmaury** [comment]
Can you take a thread dump of the IntelliJ VM and attach the result ?

**Comment by mohitsuman** [comment]
@NKozlov The logs would be available in the Output Terminal. And can you please check if it still persists for you with the latest extension ?

**Comment by sbouchet** [comment]
closing as stale
