### ISSUE TITLE
Add telemetry to Red Hat Developer Sandbox workflow

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#376]
We should report various events to telemetry when the Red Hat Developer Sandbox workflow is processed.

Events:

- get SSO token
- each of the sandbox API calls
- cluster token retrieved
- dialog closed

**Comment by sbouchet** [comment]
the journey can be viewed like this:
(complete devsandbox creation user case)

![Capture d’écran de 2022-02-24 10-13-47](https://user-images.githubusercontent.com/600414/155511256-ad5b7620-0cd2-4e79-b41b-e563877f782e.png)
