### ISSUE TITLE
Implement login from oc command line paste

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#39]
When you need to login in to a cluster, it would be fine to be able to set the parameters from the command that is copied into the clipboard from the OpenShift web console

**Comment by adietish** [comment]
The cluster login dialog could paste the login command into the form if there's no current cluster. If there is one it could ex. allow to use it by hitting a button, link etc.
Also possible would be that when pasting the command into a text field it'd extract the relevant portion (ex. when pasting the command oc login https://api.rh-us-east-1.openshift.com --token=XXXX into the "Cluster URL" it would use the url portion only)
