### ISSUE TITLE
The OpenShift and Clusters Tree view should only support single item selection

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#4]
In GitLab by @tgrall on Jan 29, 2019, 17:09

The current implementation allow the user to select multiple entries in the tree (for example multiple project, services)

This is confusing since user can right click and for example do a delete.

Since the underline technology (odo) can only send a single command, we should only allow single item selection in tree.

**Comment by sbouchet** [comment]
closing in favor of #669. if several tree items are selected, a "nothing here" label is shown indicating multiple selection can't work.
