### ISSUE TITLE
Open Console Dashboard fails for the cluster connected

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#437]
[kind/bug]

## What versions of the software are you using?
- Operating System: Mac OS 12.5.1 
- IntelliJ version: IntelliJ IDEA 2022.2.1
- OpenShift version: Developer Sandbox 4.10.11

## What did you run exactly?

Log in to the OpenShift cluster using Developer Sandbox. Right Click and run `Open Console Dashboard`

## Actual behaviour

The Open Console Dashboard opens a new tab in the browser but errors out as it open the API URL instead of the console URL.

## Expected behaviour

It should open the console URL in the new tab.

**Comment by jeffmaury** [comment]
Cannot reproduce. It opens the right URL for me.
