### ISSUE TITLE
Request for Open Console Dashboard option when logged in to the cluster is not providing username using odo v3

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-openshift-connector#444]
[kind/bug]

## What versions of software are you using?
- Operating System: Linux, Fedora 36
 - IntelliJ version: IU 2022.2.3
 - OpenShift version: 0.12.0.131

## What did you run exactly?
- Logged in to the cluster and called context menu option: Open Console Dashboard
- 

## Actual behavior
Opened URL returns this json response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/console\"",
  "reason": "Forbidden",
  "details": {
  },
  "code": 403
}
```

## Expected behavior
It should properly open openshift web console (provide proper details in the request)

**Comment by jeffmaury** [comment]
I can't reproduce on Windows and Ubuntu. Can you join a screencast ?
