### ISSUE TITLE
Show and follow log context menu items disappeared from component item after option Show Log option is executed

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-openshift-connector#460]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 36
- IntelliJ version: 2022.2.3
- OpenShift version: 0.12.0.139

## What did you run exactly?
1. logged in cluster (crc)
2. empty project in workspace
3. created Quarkus component (Quarkus java using starter app)
4. Component started in Dev mode
5. Run Show log

## Actual behavior
Show log shows app's log, but then this option and option to follow log disappear from context menu 

## Expected behavior
Show and follow log should be always available in started dev mode

**Comment by odockal** [comment]
Restarting the dev mode will bring option back. But after calling show or follow log option will again "hide" these options.

**Comment by jeffmaury** [comment]
This is per design: when you run Show log (or Follow log) it will start the odo logs commands and then Show log (or Follow logs) command is not available anymore until the odo process is not running anymore.
So the only issue here is that if you run Follow logs then this is no way to stop it.
![showlogs](https://user-images.githubusercontent.com/695993/200317493-bf545e3a-c078-493b-9907-f1433f1a63e1.gif)

**Comment by odockal** [comment]
I see, thanks for clarification. Closing.
