### ISSUE TITLE
Support podman workflow in extension using odo

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#490]
Here is the demo https://www.youtube.com/watch?v=EmN_hGkOHX4

**Comment by jeffmaury** [comment]
That's experimental (so likely buggy) should we support that yet ?

**Comment by mohitsuman** [comment]
We have support for podman with a simple workflow using odo dev running on podman. Let's add the same feature parity to IntelliJ OpenShift.

**Comment by sbouchet** [comment]
blocked by https://github.com/redhat-developer/odo/issues/6824
