### ISSUE TITLE
Can't login to a DevSandbox

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/intellij-openshift-connector#529]
- Operating System: MacOS 13
- IntelliJ version: 2022.2.3
- OpenShift version: 1.3.0.172

Trying to log in to the cluster with developer sandbox results in empty page 

![Screenshot 2023-04-11 at 21 51 49](https://user-images.githubusercontent.com/86789336/231273494-aa38fbf3-b3e6-4caf-a1c1-25a6f4271301.png)

**Comment by lgrossma** [comment]
[stacktrace.txt](https://github.com/redhat-developer/intellij-openshift-connector/files/11208962/stacktrace.txt)

**Comment by sbouchet** [comment]
closing as invalid
