### ISSUE TITLE
Can't stop dev on component after switching to a different project

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/intellij-openshift-connector#537]
Steps to reproduce:
1. Create two projects
2. In one of the projects create new component and start dev on it
3. Switch to a different project and right back to the first project using the k8s extension
4. The component is still in dev mode but does not have option to stop the dev mode

**Comment by mohitsuman** [comment]
@lgrossma Is the issue still on 1.6.0 version of the plugin ? Can you please update.

**Comment by lgrossma** [comment]
@richard0202 Could you please verify?

**Comment by adietish** [comment]
I experience this when switching clusters, too. 

1. ASSERT: have 2 clusters (ex. local crc, sandbox)
2. ASSERT: have cluster 1 set as current cluster.
3. EXEC: pick "start dev on Cluster" in ctx menu to your component
4. EXEC: switch current cluster using intellij-kubernetes or kubectl
5. ASSERT: OpenShift tree is refreshed
6. EXEC: pick "Start dev on Cluster" to your component

**Result:**
Terminal opens, dev is tried but fails reporting an existing PID already running
<img width="1076" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/e6902988-9ae3-4d70-adaf-912cc93a3168">
