### ISSUE TITLE
Add Helm Chart support similar to VSCode OpenShift Toolkit

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#539]
[kind/Feature]

## Which functionality do you think we should add?

Users should have the option to browse and install Helm Charts to the connected cluster. There should be an UI view to list all the Helm Charts and Install button with the chart information.

## Why is this needed?

As a user, I want to install a Helm Chart directly from the plugin and also should be able to browse other charts available to be installed in the cluster. Using Helm Charts, users can install databases and can link to the component created.

**Comment by adietish** [comment]
In VSCode Helm can be reached by choosing "Open Helm Chart" in the context menu to the cluster. An editor is then opened:
<img width="1346" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/056bdbfd-80e5-4e56-a72c-80039427aafc">
