### ISSUE TITLE
Add gifs/videos documentation at plugin landing page

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#546]
Currently in plugin landing page, we do not have any documentation gif. We need to add working gif/video in the landing page.

Ref: https://plugins.jetbrains.com/plugin/10485-kubernetes

**Comment by sbouchet** [comment]
for now createdtwo videos documetation :
- create nodejs component on devsandbox + debug it 
- use dev on podman

**Comment by sbouchet** [comment]
landing page can only support one youtube video, and then screenshots.
uploaded create nodejs demo on landing page.
