### ISSUE TITLE
Log in to cluster with no KUBECONFIG present does not log in.

### ISSUE THREAD

**Issue by martinszuc** [redhat-developer/intellij-openshift-connector#575]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora Linux 38 (Workstation Edition)
- IntelliJ version:  same behavior with IntelliJ IDEA 2023.2 (Ultimate Edition)  & IntelliJ IDEA 2021.2 (Ultimate Edition) 
- OpenShift version: 1.5.0 &  1.6.0 

## What did you run exactly?
Opened Intellij with Openshift connector plugin installed. 
Log in to cluster.
After submitting the URL, username, password in the Cluster login dialog nothing happens. 

## Actual behavior
 The login takes effect only after Intellij was restarted.
 Refresh button on openshift cluster has no effect. 

## Expected behavior
 Not sure if this is expected behavior. Maybe refresh would apply the login?
 
## Any logs, error output, etc?'
 Opening Intellij without KUBECONFIG gives IDE error:
java.io.IOException: Process exited with an error: 1 (Exit value: 1) {
	"message": "KUBECONFIG not found. Unable to retrieve cluster information. Please set your Kubernetes configuration via KUBECONFIG env variable or ~/.kube/config"
}

**Comment by martinszuc** [comment]
Discovered when working on integration UI test case: 'Can login to a cluster in different ways when logged out'. Login cannot be verified with this behavior.

**Comment by richard0202** [comment]
This issue still persists in IntelliJ IDEA 2023.2.1, OpenShift connector version 1.6.0.218

**Comment by lgrossma** [comment]
I can't replicate this issue on MacOS

**Comment by martinszuc** [comment]
This issue was fixed in version 1.7.0 https://github.com/redhat-developer/intellij-openshift-connector/releases/tag/1.7.0
