### ISSUE TITLE
Project starter dropdown menu is not showing

### ISSUE THREAD

**Issue by richard0202** [redhat-developer/intellij-openshift-connector#579]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora Linux 38
- IntelliJ version: IntelliJ IDEA Ultimate 2023.2.1
- OpenShift version: 1.6.0.218

## What did you run exactly?

1. Connect to the cluster
2. Create project on cluster
3. New component -> Node.js Runtime

## Actual behavior

Can´t select the Project starter, missing dropdown menu.

## Expected behavior

It should be possible to select the Project starter from dropdown menu.

## Any logs, error output, etc?

I have found out, that if you have in your project workspace only .idea folder and/or .iml files and/or .gitignore file then everything works fine as expected, but when you add any other folder or file to the project workspace, then you can´t select the Project starter.

**Comment by martinszuc** [comment]
The Project starter cannot be selected if the node js component project was already started first time and files were created/imported. Files e.g. server.js persist in Project files even after component was deleted. So this is either fixed now or desired behavior.
