### ISSUE TITLE
Logging into the cluster does not refresh the tree

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#595]
depends on https://github.com/redhat-developer/intellij-common/issues/201

**Steps:**
1. ASSERT: make sure that you are not logged into your current cluster
2. EXEC: launch the plugin, unfold the root (cluster) node
3. ASSERT: tree shows "Please log into the cluster"
4. EXEC: pick "Log into the cluster" in the context menu and log in
5. ASSERT: dialog is closed, look at the tree

**Result:**
The tree still shows "Please log in to the cluster". "Refresh" doesnt help, I have to restart the IDE. 
<img width="510" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/3ad964b1-4473-4117-84e9-245dc60afc90">

**Comment by martinszuc** [comment]
Earlier than Commits on Oct 5, 2023 for IJ Openshift: I used to remove /.kubo/config for a "logout" from cluster:
![old-logout (1)](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/5bb898c7-f5c7-477d-a309-5620b07f92c0)

Nowadays after removing the kube config it just fails to load after refresh.  (it doesnt default to the kubernetes.defuult link). The cluster link defualts itself only when I remove .kube/config WHILE THE PROJECT IS CLOSED! : 
![image](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/cd10e41f-e7f9-4642-bec8-d82213427ac2)

As for logging in, before Oct 5, it seemed to matter if I deleted whole .kube or just .kube/config file. With just the config file deleted, the login would default correctly in real time and next login would work correctly as well. 
After Oct 5 this doesnt work and needs IDE restart for login. 

Also closing and reopening the project seems to refresh the tree correctly just as restart. 

Sooo i believe the change that affected this, was somewhere between Oct 5-6 and now. Wanted to share my findings.

**Comment by adietish** [comment]
> Sooo i believe the change that affected this, was somewhere between Oct 5-6 and now. Wanted to share my findings.

@martinszuc thanks sharing. I'll try to fix your issue, too.

**Comment by adietish** [comment]
both use cases have different causes:
* removing the config file does not trigger a refresh of the tree because of a check in the `ConfigWatcher`. If the `config` is null, no update happens (config file was deleted, `config` is therefore `null`)
```java
  @Override
    public void run() {
        runOnConfigChange((Config config) -> {
-->       if (config != null) {
                listener.onUpdate(this, config);
            }
        });
    }
```
* changing the config (update the token) triggers a refresh but other flaws caused the update to fail.

**Comment by adietish** [comment]
to fix this I created https://github.com/redhat-developer/intellij-common/pull/201
