### ISSUE TITLE
Login: retrieve a proper error when login is failing

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#6]
In GitLab by @tgrall on Jan 31, 2019, 14:54

When the cluster is not available the plugin return a "System -1" error.
We shoudl return a proper error, the one returned by ODO.

**Comment by mohitsuman** [comment]
The current release of the IntelliJ OpenShift returns the proper error response as thrown by odo. Hence closing the issue.
