### ISSUE TITLE
Detailed error output does not appear 

### ISSUE THREAD

**Issue by umutcann** [redhat-developer/intellij-openshift-connector#62]
Hi,

I notice two bugs.

One of them is that if push take error due to any reason, error reason does not appear on IntelliJ Odo terminal. For example I could see error reason on command prompt but I could not see on IntelliJ Odo terminal.

<img width="325" alt="2" src="https://user-images.githubusercontent.com/18632831/59285883-62514180-8c77-11e9-86b0-725577795365.PNG">

<img width="464" alt="1" src="https://user-images.githubusercontent.com/18632831/59285864-5c5b6080-8c77-11e9-85b8-cb7b8cb616a7.png">

The other one is that, when I try to login my own openshift cluster, I could not view our projects after click on OK. After restart IntelliJ I could see projects in Openshift. I think it isn't working dynamically. 

<img width="405" alt="3" src="https://user-images.githubusercontent.com/18632831/59286464-78133680-8c78-11e9-9b02-c72c90b0b81d.PNG">

Thanks.

**Comment by umutcann** [comment]
Hi,

Additionally projects and applications view like intertwined.

<img width="203" alt="Capture5" src="https://user-images.githubusercontent.com/18632831/59518416-44314e80-8ece-11e9-9195-a5239ec6dc57.PNG">

**Comment by jeffmaury** [comment]
Tried on both a local cluster (cdk) and a remote one (employee.openshift.com) and even if the display is first blinking I can see the projects. Will try with an odo deployment on a local cluster

**Comment by jeffmaury** [comment]
Tried on both a local cluster (cdk) and a remote one (employee.openshift.com) and even if the display is first blinking I can see the projects. Will try with an odo deployment on a local cluster

**Comment by umutcann** [comment]
Do you have any comments for other issues above?

**Comment by umutcann** [comment]
@mohitsuman you may close the issue.
