### ISSUE TITLE
Start dev on Podman does not work when odo fails to fetch version

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/intellij-openshift-connector#637]
When I try to start dev on Podman I get an error message:
`unable to access podman. Do you have podman client installed and configured correctly? cause: exec: "podman": executable file not found in $PATH`
However, if I run the same command from terminal, starting dev works well.

I am running intellij 2023.2.4 (Ultimate Edition) on MacOS 14.1.1

**Comment by sbouchet** [comment]
@lgrossma : can you paste the result of the 'About' action ? ( Using context menu on Cluster tree item )

**Comment by lgrossma** [comment]
sure, sorry for the delay

/Users/lgrossma/.odo/cache/3.15.0/odo-darwin-amd64 version
==============================================
⚠  unable to fetch the podman client version
==============================================
odo v3.15.0 (10b5e8a8f)

Server: https://api.ocp2.adapters-crs.ccitredhat.com:6443
Kubernetes: v1.26.5+7d22122

**Comment by sbouchet** [comment]
thanks. i assume if you just try `podman version` in command line it runs fine ?
