### ISSUE TITLE
Add support for debug

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#64]
[kind/Feature]

## Which functionality do you think we should add?

Users should be able to debug their components. So from a running component, user
could launch a debug that will switch the component in debug mode and launch and connector the debugger from the local IDE

## Why is this needed?

This is a requirement from developers

This will require odo changes.

**Comment by mohitsuman** [comment]
We have the support for Java and NodeJS apps in the extension workflow. Closing this issue. Debug support for other languages will be opened as a separate issue.
