### ISSUE TITLE
Add 'Switch User' command to OpenShift Application Explorer

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#66]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Allow to switch cluster context on the cluster node.
For more details, see https://github.com/redhat-developer/vscode-openshift-tools/issues/975

## Why is this needed? 

To get aligned with VSCode OpenShift Connector

**Comment by sbouchet** [comment]
closing as we now depend on intellij-kubernetes to manage cluster contexts (#319)
