### ISSUE TITLE
Cant run "odo"

### ISSUE THREAD

**Issue by ebacklund** [redhat-developer/intellij-openshift-connector#68]
## What versions of software are you using?
- Operating System: MacOS Mojave (10.14.6)
- IntelliJ version: 2018.3
- OpenShift version: v3.11.88

## What did you run exactly?
Install plugin/odo

## Actual behavior
odo install error.

I have odo installed:
<username>$ which odo
/usr/local/bin/odo

<username>$ odo version
odo v0.0.20 (bd3e74a4)

When I try to use plug in, I continually get asked to download odo. If I select 'Yes' it will download it to my user home directory, however it will continually ask me to install it. If I select 'No' any interaction results in error "Error: Cannot run program "odo" (in directory ".") error=2, No such file or directory"

## Expected behavior
plugin to find and execute odo

**Comment by edeandrea** [comment]
I get the same thing, but a little bit different

- macOS Mojave (10.14.6)
- odo version: 1.0.0-beta4 (I also tried with 0.0.20 and get the exact same thing)
- IntelliJ version: 2019.2 Build # IU-192.5728.98, built on July 23, 2019 (Runtime version 11.0.3+12-b304.10 x86_64
- Openshift version 3.11.104

Whenever the OpenShift view is displayed I continually get a dialog that says `Odo not found, do you want to download odo?`. Upon clicking _yes_ I then get an error that says `Error: org.apache.commons.compress.compressors.CompressorException: No Compressor found for the stream signature.`

I downloaded & installed odo [from the instructions](https://github.com/openshift/odo#installing-odo): `curl -L https://github.com/openshift/odo/raw/master/scripts/installer.sh | bash`
