### ISSUE TITLE
As a User, i want to be able to switch context present on my .kubeconfig file

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#681]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
After #661, next step is to be able to switch contexts ( clusters ) if they exists in .kubeconfig file. 
If not, there is already a "login to cluster" action on cluster root element.

## Why is this needed? 
after this is done, we can remove the dependecy to Intellij Kubernetes

**Comment by adietish** [comment]
duplicate to #639. 
Closing.
