### ISSUE TITLE
Fix Action labels for kubernetes clusters

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#701]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
When using a kubernetes-based cluster, i would like to see "Create Namespace/Change namespace" and not Openshift "project" labels in context menus.

**Comment by adietish** [comment]
This is to be fixed in #237 as context menu entries and labels in the dialog are closely related implementation-wise.

**Comment by adietish** [comment]
fixed by #680. Closing.
