### ISSUE TITLE
bug: Changing current active project to a non-existent one

### ISSUE THREAD

**Issue by martinszuc** [redhat-developer/intellij-openshift-connector#715]
[kind/bug]

## What versions of software are you using?
- Operating System: Ubuntu 22 
- IntelliJ version: ULTIMATE 2023.3.4 
- Extension version: 1.7.3-20240222
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:
Server: https://api.sandbox-m4.g2pi.p1.openshiftapps.com:6443
OpenShift: 4.14.1
Kubernetes: v1.27.6+f67aeb3

## What did you run exactly?
Change current active project to a project which is non-existent or has not been created yet.
![Screenshot from 2024-02-22 23-29-20](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/abe843bc-fe95-4fba-b3c2-7b36dcfce7c5)

## Actual behavior
Success notification appears:
![Screenshot from 2024-02-22 23-29-37](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/b0959363-995d-46eb-8eae-b253a5cdc034)

After the notification , I got **logged out** of the cluster 
![Screenshot from 2024-02-22 23-30-07](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/effbd5e8-3cea-4984-b249-7f4aff6e3894)

## Expected behavior maybe ?

Don't allow user to press "Change" button if project doesn't exist in the "Change Active Project" dialog.  This failure to change the project also logs out of the cluster which could not be the desired behavior imo.

**Comment by adietish** [comment]
There are 2 problems here:

1) we're using odo to change the active project. The only way with odo to change the current/active project is to change it in the kube config (~/.kube/config). This always succeeds, it's only the subsequent refresh of the resource tree and the retrieval of the existing current/active project that fails. The user is therefore notificed of an erroneous success

2) retrieving the current project (which is a non-existing project) in the tree fails and leads to the tree displaying "please log in"

**Comment by adietish** [comment]
In other words 1 isn't an issue. One can argue about the success notification being misleading (vscode does not notify of a successful change, it does not notify at all).
2 on the other hand is an issue which needs fixing.

**Comment by martinszuc** [comment]
@adietish @sbouchet the logging out after project deletion could be related to https://github.com/redhat-developer/intellij-openshift-connector/issues/719

**Comment by martinszuc** [comment]
#722 fixes this for me
