### ISSUE TITLE
Invalid plugin descriptor 'plugin.xml' in Marketplace

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-openshift-connector#730]
[kind/bug]

As reported by verification results for the OpenShift Toolkit by Red Hat plugin by JetBrains:

Configuration of OpenShift Toolkit by Red Hat 1.8.0 has 1 defect
Invalid plugin descriptor 'plugin.xml'. The plugin id should not contain the word 'intellij'.

**Comment by sbouchet** [comment]
this error is gone.
it was also impossible to fix as the plugin ID can't change between versions as it's used as ID for updates.
