### ISSUE TITLE
Unable to login: failed to verify certificate

### ISSUE THREAD

**Issue by martinszuc** [redhat-developer/intellij-openshift-connector#862]
## What versions of software are you using?
- Operating System: Fedora
- IntelliJ version: IntelliJ IDEA 2023.3.4 (Ultimate Edition)
- Extension version: 1.9.1-20240702-013100
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:  https://api.ocp2.adapters-crs.ccitredhat.com:6443

## What did you run exactly?

- Log in to the cluster using the extension
![image](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/a152bc76-87cb-4d2d-aecf-5bcb9adaaf32)

## Actual behavior

![image](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/86bc8ed9-3ada-40b5-ac04-99eb48eedca0)

## Any logs, error output, etc?

mszuc@fedora:~/.odo/cache/3.16.1$ ./odo login -p x -u x https://api.ocp2.adapters-crs.ccitredhat.com:6443
Connecting to the OpenShift cluster

 x  tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by sbouchet** [comment]
i can reproduce and even confirm that might be a regression from odo, since i get a different  and expected result with odo 3.15.0
```
/home/sbouchet/.odo/cache/3.15.0/odo login -p x -u x https://api.ocp2.adapters-crs.ccitredhat.com:6443 --insecure-skip-tls-verify
Connecting to the OpenShift cluster

Login failed (401 Unauthorized)
Verify you have provided correct credentials.
```

**Comment by sbouchet** [comment]
opened https://github.com/redhat-developer/odo/issues/7257.
actual workaround is to log in using another CLI (oc, odo 3.15.0)

**Comment by sbouchet** [comment]
another solution might be to start the move from odo to something else, like [OC ](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/)
