### ISSUE TITLE
Support  2024.2 

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#889]
Current Next EAP nightly ( 2024.2 ) is failing due to major changes. 
With RC out, time to get  this fixed. 

## What versions of software are you using?
- Operating System:
- IntelliJ version:
- Extension version:
- Are you targeting a kubernetes or an Openshift cluster ? If possible, provide its version:

**Comment by sbouchet** [comment]
message is (from build output)
```
> Task :verifyPluginConfiguration

Gradle IntelliJ Plugin 1.x does not support building plugins against the IntelliJ Platform 2024.2+ (242+).

Please upgrade your configuration to use the IntelliJ Platform Gradle Plugin 2.0.0 or higher!
[gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
```

**Comment by adietish** [comment]
IC-2024.2 was released yesterday
